name: fiestafinderflutter
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.4.8
  logger: ^2.5.0
  cupertino_icons: ^1.0.8
  firebase_core: ^3.12.0
  cloud_firestore: ^5.6.4
  google_maps_flutter: ^2.5.0
  share_plus: ^7.2.1
  flutter_svg: ^2.0.4
  lottie: ^2.6.0
  chewie: ^1.7.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.9.2  # Especifica la versión de flutter_launcher_icons

flutter:
  uses-material-design: true
  assets:
    - assets/ff.png
    - assets/inicio3.mp4
    - assets/spinner.json
    - assets/user.json


